### ISSUE TITLE
Need Help !

### ISSUE THREAD

**Issue by AEK-BKF** [rinvex/laravel-contacts#6]
Hi,
I'm wondering what does these mean : national_id_type, national_id 
i.e from where you get data ?

Also in your Contact Model you set relatives() and backRelatives() with the same function.
Could you pelase explain how does it work ?

Thanks.

**Comment by Omranic** [comment]
national_id is like social security number, and we've both id & type because some countries don't have the same system like US so it's called something else, so you can specify what type of ID and it's number. That's what's it's all about.

And for the relatives question, it's easy: a person has multiple relatives, right? And at the same time, the same person is considered a relative for some other people. Since we're using the same model, we're defining different relationships to track both, it's kind of circular relationship. Let me know if you've better thoughts about this :)

**Comment by AEK-BKF** [comment]
Got It ! Thank you so much :)
